### ISSUE TITLE
Topography module not working properly with negative values

### ISSUE THREAD

**Issue by flohorovicic** [cgre-aachen/open_AR_Sandbox#19]
**What I am trying to do**:

Add negative `TopoModule.min_height` values to show sea level at beginning at 0 m.

**Problem**: even if I set `TopoModule.min_height` (also implemented a slider for it), the generated map still starts at 0 (see image). 

**Commit**: befb26104fecd5249462df6159802ba0579a2a0e

I think it is related to the `TopoModule.set_norm()` method, but could not figure out how...

(Note: in the image, `TopoModule.min_height` is actually set to -200)

![image](https://user-images.githubusercontent.com/1070677/102705843-29daec80-428c-11eb-8cb4-dc9517aa60c6.png)

**Comment by flohorovicic** [comment]
Refers to this commit: befb26104fecd5249462df6159802ba0579a2a0e

**Comment by danielsk78** [comment]
solved in commit b71b6cf73d70b0afd17d898547da9548806e08e9
