### ISSUE TITLE
Projecting Leapfrog model into sandbox

### ISSUE THREAD

**Issue by hentsd** [cgre-aachen/open_AR_Sandbox#31]
Hey, is there a possibility to project a model made in Leapfrog into the sandbox? 
The idea is to have ore bodies in the model which, in my opinion, are much easier to model in Leapfrog.

**Comment by danielsk78** [comment]
Hi @hentsd,
For the moment, there is no support with Leapfrog. But it would be a nice addition to the Sandbox.
If you can create a Matplotlib figure from a Leapfrog model, then the sandbox link would be straight forward. If this is not the case, then you would need to see how this link is possible. 
From our side, we can just guide you on creating the modules and the connection to the Sandbox (check the tutorials), but the link to Leapfrog would be something that you need to look and later commit to this repository. 
Let me know your thoughts on this if you want to develop this part of the Sandbox.
Best wishes, 
Daniel

**Comment by flohorovicic** [comment]
Hi @hentsd,

Quick addition to comment by Daniel: I think @AlexanderJuestel implemented the functionality to load Leapfrog models into gemgis - maybe check there. If this is possible, then the visualisation in the sandbox should also work.

**Comment by flohorovicic** [comment]
https://github.com/cgre-aachen/gemgis

**Comment by AlexanderJuestel** [comment]
Hey, 
check here: https://github.com/cgre-aachen/gempy/issues/570 ;)

**Comment by hentsd** [comment]
GemGIS worked like a gem and I managed to visualize the Leapfrog model as a PyVista mesh. What I'm having a bit trouble now is saving the mesh to visualize it in the sandbox. 
In what format and how should I save the mesh so that it would be supported for the sandbox?

**Comment by danielsk78** [comment]
Hi @hentsd,
The sandbox is connected to Gempy. That means that you need to create a Gempy model out of the leapfrog model. 
If you already have the mesh in PyVista, it would be possible to extract the interface points and orientations from here and then create your Gempy model. This means that from pyvista, you could sample the mesh's surface as interfaces, and pyvista also gives the option to get the surface normal from the mesh - this will be your orientations. With these, you can already create your gempy mesh. 

From the sandbox perspective is not too much to do, unless that you can create a matplotlib figure directly from the mesh. This means that you can show your matplotlib figure on the sandbox through the ```Projector``` class by doing:
```
from sandbox.projector import Projector
projector = Projector(...calibration files)
.
.
.
# create your matplotlib figure
projector.frame.object = figure
projector.trigger() 
# This will overwrite and show any matplotlib figure on the sandbox

```
On the other hand, using [GemGIS](https://github.com/cgre-aachen/gemgis) can help creating a Gempy model from a leapfrog mesh, and you could help us having this workflow. 
A good place to start is https://gemgis.readthedocs.io/en/latest/getting_started/tutorial/15_opening_leapfrog_meshes_and_gocad_tsurfaces.html
