### ISSUE TITLE
Sandbox install instructions

### ISSUE THREAD

**Issue by devlk2** [cgre-aachen/open_AR_Sandbox#48]
During the process of setting up the sandbox with all necessary data one is forced to install via a Windows system all related packages under the point "Standard packages" with the command "pip install -r requirements.txt". 
That is actulally not working!

Therefore the right command would be: "pip install -r /path/to/requirements.txt"

**Comment by danielsk78** [comment]
We need to update the README file to specify exactly where to run the  'pip install -r requirements.txt'.
