### ISSUE TITLE
Installation issue Windows system

### ISSUE THREAD

**Issue by devlk2** [cgre-aachen/open_AR_Sandbox#53]
If I tried to follow the installation instruction than it happens when I am finished and open a certain tutorial that I run in the third cell into a error meassage called: "NameError: name 'PyKinectRuntime' is not defined"
The weired thing is, that if I try it now again with the preinstalled env by Daniel it runs not into that issue. I deinstalled and installed the pykinect2 specific file which has also manually to be changed  several times but nothing changes. In the end I started copying the files and finally all related folders from  the pykinect2 package into my new generated env and still the message appears!

**Comment by SimonVirgo** [comment]
I can confirm the issue (Windows, fresh environment) I will have a look now

**Comment by SimonVirgo** [comment]
commenting out line 2866 in pykinectv2 does the trick. No idea why the version check fails though...
```python
# from comtypes import _check_version; _check_version('')
```

**Comment by SimonVirgo** [comment]
@devlk2 can you confirm that solves the issue for you?

**Comment by aapopei** [comment]
> commenting out line 2866 in pykinectv2 does the trick. No idea why the version check fails though...
> 
> ```python
> # from comtypes import _check_version; _check_version('')
> ```

It gives me

`AttributeError: module 'time' has no attribute 'clock'`
