### ISSUE TITLE
Gempy version not compatible with Pandas Version

### ISSUE THREAD

**Issue by VLSAR24** [cgre-aachen/open_AR_Sandbox#68]
The installed pandas version is 1.3.4 in the sandbox environment. The gempy library is unable to run and gives an error 'GemPy requires pandas version < 1.4.0. The new pandas release is not compatible with GemPy. We're actively working on this issue for a future release.'
![List packages](https://user-images.githubusercontent.com/107347121/173227784-03143a71-9c8d-4aa7-81cb-00f372263cf2.png)
![Error](https://user-images.githubusercontent.com/107347121/173227818-6a4948e4-5c88-4097-9341-648f187de55c.png)

**Comment by Japhiolite** [comment]
Are you certain, you're looking at the same environment? That error only appears if pandas is > 1.4.0

**Comment by VLSAR24** [comment]
Hello @Japhiolite,
Yes. I am looking at the same environment (sandbox-env). I have tried creating the whole environment again but am still facing the same error.

**Comment by Japhiolite** [comment]
That's strange. Just to be sure: In the notebook, where you import gempy, can you in a cell above the import gempy statement `import pandas` and print the version `pandas.__version__`?

**Comment by VLSAR24** [comment]
@Japhiolite That is embarrassing. A higher version of python is currently installed (1.4.2). Thank you very much. I will try to downgrade the version.
