### ISSUE TITLE
ValueError: Margin parameter 'margin' only takes integer and tuple values, not values of not <class 'list'>.

### ISSUE THREAD

**Issue by Geleandro** [cgre-aachen/open_AR_Sandbox#72]
Hello, can anyone help me? I am not able to calibrate the projector, this mage error appears. Could it be an installation error? Is there a package missing? or is it configuration? I'm using Ubuntu and Kinect V1. thanks

**Comment by danielsk78** [comment]
Hi @Geleandro,
Thank you for opening this issue.  This error has to do with 'Panel' version. It appears that we need to update the type class of the margin when creating the Projector window. Currently, these are 'List' , but it can only accept 'Tuple'.
A quick fix is to downgrade Panel until the error no longer appears.
We will fix this as soon as possible.
Cheers, 
Daniel

**Comment by danielsk78** [comment]
@Geleandro 
This error should be fixed now with the latest version of the sandbox. Please check if this works. I'll close this issue but if the error persists, feel free to open it again.
Cheers, 
Daniel.
